model:
  method: dream
  n_hidden: 64
  n_layer: 2
  act: F.relu
  dropout: 0.5
  norm_info: ~
  input_layer: false
  output_layer: false

  k_topology: 5
  k_proximity: 20
  temperature: 0.5
  d_max: 5

training:
  lr: 1e-2
  weight_decay: 5e-4
  n_epochs: 500
  patience: ~
  criterion: metric
  warmup_epochs: 6

  lambda_cl: 0.7
  cl_temperature: 0.5
  warmup_epochs_cl: 20
  drop_edge_rate1: 0.9
  mask_feat_rate1: 0.8
  drop_edge_rate2: 0.9
  mask_feat_rate2: 0.8

dataset:
  name: Flickr
  sparse: true